title: SISTFers

description: >
  35613.github.io jekyll site

baseurl: ""

url: "http://35613.github.io"

github_username: 35613

gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

theme: minima

markdown: kramdown

kramdown:
  input: GFM

timezone: KR
